CREATE TABLE AUTOR
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	NACIONALIDADE VARCHAR(30) NOT NULL
);

CREATE TABLE EDITORA
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL
);

CREATE TABLE CATEGORIA
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	TIPO_CATEGORIA VARCHAR(50) NOT NULL
)

CREATE TABLE LIVRO
(
	ISBN VARCHAR(20) NOT NULL PRIMARY KEY,
	TITULO VARCHAR(100) NOT NULL,
	ANO_PUBLICACAO DATETIME NOT NULL,
	FK_EDITORA INTEGER NOT NULL,
	FOREIGN KEY (FK_EDITORA) REFERENCES EDITORA(ID),
	FK_CATEGORIA INTEGER NOT NULL,
	FOREIGN KEY (FK_CATEGORIA) REFERENCES CATEGORIA(ID)
);

CREATE TABLE LIVROAUTOR
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	FK_LIVRO VARCHAR(20) NOT NULL,
	FOREIGN KEY (FK_LIVRO) REFERENCES LIVRO(ISBN),
	FK_AUTOR INTEGER NOT NULL,
	FOREIGN KEY (FK_AUTOR) REFERENCES AUTOR(ID) 
);