CREATE TABLE DESCOBRIDOR
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL
);

CREATE TABLE ERA
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
);

CREATE TABLE PAIS
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL
);

CREATE TABLE GRUPO
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL
	
);

CREATE TABLE DINOSSAURO
(
  	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	TONELADAS INTEGER NOT NULL,
	INICIO INTEGER NOT NULL,
	FIM INTEGER NOT NULL,
	ANO_DESCOBERTA INTEGER NOT NULL,
	FK_GRUPO INTEGER NOT NULL,
	FOREIGN KEY (FK_GRUPO) REFERENCES GRUPO(ID) ,
	FK_ERA INTEGER NOT NULL
	FOREIGN KEY (FK_ERA) REFERENCES ERA(ID),
	FK_DESCOBRIDOR INTEGER NOT NULL,
	FOREIGN KEY (FK_DESCOBRIDOR) REFERENCES DESCOBRIDOR(ID),
	FK_PAIS INTEGER NOT NULL,
	FOREIGN KEY (FK_PAIS) REFERENCES PAIS(ID)
);