CREATE DATABASE AulaAtos;
DROP DATABASE AulaAtos;

DROP TABLE ALUNOS;

CREATE TABLE ALUNOS
(
	id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	IDADE INTEGER
);

ALTER TABLE ALUNOS
ADD RG VARCHAR(12);

CREATE TABLE CURSOS
(
    ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
    NOME VARCHAR(30) NOT NULL,
    CARGA_HORARIA INTEGER NOT NULL,
    ATIVO BIT DEFAULT 1,
    DESCRICAO TEXT
);

CREATE TABLE DISCIPLINAS
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	CARGA_HORARIA INTEGER  NOT NULL,
	FK_CURSO INTEGER NOT NULL,
	FOREIGN KEY (FK_CURSO) REFERENCES CURSOS(ID) 
);

CREATE TABLE MATRICULAS
(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	FK_ALUNO INTEGER NOT NULL,
	FK_CURSO INTEGER NOT NULL,
	FOREIGN KEY (FK_ALUNO) REFERENCES ALUNOS(ID),
	FOREIGN KEY (FK_CURSO) REFERENCES CURSOS(ID)
);

